#!/usr/bin/env bash
# Install nginx on my 1178-web-01 server.
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow http
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart
