#!/usr/bin/env bash
# Configuration Nginx server so that /redirect_me is redirecting to another page.
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow http
sudo chgrp -R ubuntu /usr/share/nginx/html
sudo chmod -R g+w /usr/share/nginx/html

echo "Holberton School" > /usr/share/nginx/html/index.html
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://twitter.com permanent;' /etc/nginx/sites-available/default

sudo service nginx start
