#!/usr/bin/env bash
# Configuration Nginx server so that /redirect_me is redirecting to another page.
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow http

echo "Holberton School" > /var/www/html/index.html
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://twitter.com permanent;' /etc/nginx/sites-available/default

sudo service nginx start
