#!/usr/bin/env bash
# Configuration my Nginx server to have a custom 404 page that contains a string.
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow http
sudo chgrp -R ubuntu /usr/share/nginx/html
sudo chmod -R g+w /usr/share/nginx/html
echo "Holberton School" > /var/www/html/index.html
# Redirection and error
printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /404_error.html;
    location /404_error.html {
        internal;
    }
}" > /etc/nginx/sites-available/default
# Restart
sudo service nginx restart
