#!/usr/bin/env bash
# Install and configuring HAproxy on my lb-01 server.
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.5
sudo apt-get update
sudo apt-get -y install haproxy=1.5.\*
sudo echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo echo -e "
frontend fronthaproxy
         bind *:80
         mode http
         default_backend backnodes
backend backnodes
         balance roundrobin
         server 1178-web-01 54.160.217.25:80 check
         server 1178-web-02 3.87.244.249:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
