#!/usr/bin/env bash
# Requirement: Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs.
# Bug: sudo nginx status returns 'not running'; netstat -lpn does not show port 80.
sudo service nginx start
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
