#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
# and the 9th iteration, displays Holberton School and then Hi on a new line.
i=0
while((i<=10)); do
	if(($i == 9)); then
		echo "Hi"
	else
		echo "Holberton School"
	fi
	i=$((i+1))
done
