#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
i=1
while((i<=10)); do
	if((i==4)); then
		echo -e "bad luck"
	elif((i==8)); then
		echo -e "good luck"
	else
		echo "Holberton School"
	fi
	i=$((i+1))
done
