#!/usr/bin/env bash
# This script is displaying numbers from 1 to 20.
i=1
while((i<=20)); do
	echo $i
	case $i in
		4) echo -e "bad luck from China";;
		9) echo -e "bad luck from Japan";;
		17) echo -e "bad luck from Italy";;
	esac
	i=$((i+1))
done
