#!/usr/bin/env bash
#This Bash script that configures an Ubuntu server with the below requirements.
cp /etc/hosts mynewhosts
sed -i s/127.0.0.1/127.0.0.2/ mynewhosts
echo -e "8.8.8.8"	"facebook.com" >> mynewhosts
cp -f mynewhosts /etc/hosts
