#!/usr/bin/env bash
# Run Nginx as Nginx and make your fix short and sweet.
sudo chmod 644 /etc/nginx/nginx.conf
pkill -f apache2
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
